spring:
  application:
    name: checkout-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/checkout_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
          fetch_size: 50
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

server:
  port: 8082
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  level:
    com.tesis.ecommerce: INFO
    org.springframework: WARN
    org.hibernate: WARN

payment:
  simulator:
    decline:
      enabled: false
      amount: 29.99

rabbitmq:
  listener:
    default-requeue-rejected: true
