spring:
  application:
    name: core-api
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/core_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080
  servlet:
    context-path: /

jwt:
  secret: "my-super-secret-key-that-should-be-at-least-32-characters-long-in-production"
  expiration: 86400000

cors:
  allowed-origins: "http://localhost:3000,http://localhost:8000"

logging:
  level:
    root: INFO
    com.tesis.ecommerce: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
